fix a build error
"error CS0246: The type or namespace name 'DeviceConnectionException' could not be found (are you missing a using directive or an assembly reference?)"