build.cake: fix an error (#492)
Error: Error(s) occurred when compiling build script:
.build/build.cake(82,42): error CS1503: Argument 2: cannot convert from 'bool' to 'Cake.Common.IO.DeleteDirectorySettings'