GHA: run on Mac OS 13
* to fix strange warnings and errors in BLE.Client.Maui (see below)
* macos-latest is currently at 12.7

ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 16.4.7107 is Xcode 14.3 or later.
The current Xcode version (found in /Applications/Xcode_14.2.app/Contents/Developer) is 14.2.
[/Users/runner/work/dotnet-bluetooth-le/dotnet-bluetooth-le/Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj::TargetFramework=net7.0-ios]
ILLINK : warning MT0079: The recommended Xcode version for Microsoft.MacCatalyst 16.4.7107 is Xcode 14.3 or later.
The current Xcode version (found in /Applications/Xcode_14.2.app/Contents/Developer) is 14.2.
[/Users/runner/work/dotnet-bluetooth-le/dotnet-bluetooth-le/Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj::TargetFramework=net7.0-maccatalyst]
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information.
[/Users/runner/work/dotnet-bluetooth-le/dotnet-bluetooth-le/Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj::TargetFramework=net7.0-ios]
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 16.4 SDK (shipped with Xcode 14.3).
Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).
[/Users/runner/work/dotnet-bluetooth-le/dotnet-bluetooth-le/Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj::TargetFramework=net7.0-ios]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 16.4 SDK (shipped with Xcode 14.3).
Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).
[/Users/runner/work/dotnet-bluetooth-le/dotnet-bluetooth-le/Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj::TargetFramework=net7.0-ios]
Error: /Users/runner/.dotnet/sdk/7.0.402/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(86,5):
error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
[/Users/runner/work/dotnet-bluetooth-le/dotnet-bluetooth-le/Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj::TargetFramework=net7.0-ios]